name = "protfilo1"
pages_build_output_dir = "."
compatibility_date = "2024-04-05"

[[d1_databases]]
binding = "BLOG_DB"
database_name = "optics_blog_db"
database_id = "3a2c9140-a720-408c-9df4-33da9952f19b" # The user will need to update this after running wrangler d1 create
